### ISSUE TITLE
Publication d'articles par les éditeurs

### ISSUE THREAD

**Issue by manuszep** [manuszep/SEL-Website#20]

**Comment by BernyCawette** [comment]
tu as déjà une idée de quand tu pourras faire l'implémentation et la mise en ligne ?

**Comment by manuszep** [comment]
Non pas encore. J'ai commencé mais il faut trouver le temps. Mi-mai peut-être.

**Comment by manuszep** [comment]
Hello Bernard,

Juste pour te dire que ça avance bien pour les articles.
Les fonctionalités sont là et il ne reste qu'à tester. Encore 2-3 jours et c'est bon.

Bonne soirée
Manu
