### ISSUE TITLE
infos de contact

### ISSUE THREAD

**Issue by Pinkilla** [manuszep/SEL-Website#29]
« Votre profil est bien vide. Cliquez sur le petit crayon à droite de votre nom en haut de cette page pour modifier vos données. » ce n'est pas un petit crayon, il faut cliquer sur son nom puis sur modifier

**Comment by Pinkilla** [comment]
en fait, il y a deux possibilités (tu le sais):

* le crayon à gauche de la page, à droite du nom;
* modifier à droite de la page dans le menu déroulant sous le nom

il faudrait reformuler: 

*Votre profil est bien vide. Cliquez sur le petit crayon à droite de votre nom en haut **à gauche** de cette page pour modifier vos données. Vous pouvez également cliquer sur votre nom en haut **à droite** de la page, puis sur modifier.*

(la deuxième phrase est facultative)

**Comment by manuszep** [comment]
Tu as raison. Je vais essayer de trouver une formulation bien claire et complète. Quitte à avoir un écran vide, autant s'en servir pour donner de l'info utile.
