### ISSUE TITLE
ajout d'une offre / date expiration

### ISSUE THREAD

**Issue by Pinkilla** [manuszep/SEL-Website#32]
je ne peux pas mettre de date d'expiration. le format est incorrect. j'essaie:
* 01/08/2017
* 01/08/17
* 01082017
* 01-08-2017

**Comment by Pinkilla** [comment]
il semblerait que ce soit aaaa-mm-jj le format.

**Comment by manuszep** [comment]
Tu es sous FireFox j'imagine. Je viens d'essayer et ça ne passe pas en effet.
Bizarrement, sous Chrome, je peux encoder la date en fr (01/08/2017) et ça fonctionne.

**Comment by Pinkilla** [comment]
c'est étrange que ça dépende du browser

**Comment by manuszep** [comment]
Le champ date n'est pas une spécification officielle. C'est un concept de Google (bien pratique je trouve). Je vais donc devoir me rabattre sur un calendrier javascript.
