### ISSUE TITLE
faq / filtrer

### ISSUE THREAD

**Issue by Pinkilla** [manuszep/SEL-Website#34]
Tu dis: 

> Pour chercher un type ou une catégorie de service en particulier, il suffit de déployer le menu Filtrer qui se trouve dans l'en-tête de la page Services, à droite du titre.

chez moi le menu est visible et il me suffitt de cliquer sur le bouton filtrer. j'écrirais: 

> Pour rechercher des services, faites vos choix en tête de la page *Services* dans « Type de service », « Domaine » ou « Catégorie » et cliquez sur le bouton « Filtrer »

en passant tu peux mettre une majuscule à domaine.

**Comment by manuszep** [comment]
Juste, j'ai rendu les filtres visibles par défaut. Sinon personne ne les aurait trouvés.
Bien vu Sherlock
