### ISSUE TITLE
orthographe et typo

### ISSUE THREAD

**Issue by Pinkilla** [manuszep/SEL-Website#35]
je rassemble toutes les typos (j'en ai une pour le moment) dans cette même issue. 

* tu écris « trainer » en orthographe réformée et c'est très bien… fait de même quelques mots plus loin pour « apparaitra ».

**Comment by manuszep** [comment]
J'écris en orthographe de vieux en général. Je traîne à m'adapter.
L'erreur est donc sur le premier :)
