### ISSUE TITLE
Modifications des questions publiques par tous les users ?

### ISSUE THREAD

**Issue by jmvarvenne** [manuszep/SEL-Website#38]
J'ai pu entrer dans l'écran de modification des questions publiques.  Est-ce possible et normal pour tous les utilisateurs ?

**Comment by manuszep** [comment]
C'est un test que tu as fait hier ? J'ai corrigé ça entre-temps.
Si c'est d'aujourd'hui, il y a un souci quelque-part !

**Comment by jmvarvenne** [comment]
J'avais testé hier.  Effectivement, ce n'est plus possible aujourd'hui.

2017-03-08 15:42 GMT+01:00 Emmanuel Szép <notifications@github.com>:
