### ISSUE TITLE
Redirection vers questionsante.org.../sels.pdf ne fonctionne pas

### ISSUE THREAD

**Issue by jmvarvenne** [manuszep/SEL-Website#39]
Le lien ' consulter la brochure éditée par la Communauté française' de la page d'accueil ne fonctionne pas.

![fisel-redirection-sels](https://cloud.githubusercontent.com/assets/26278608/23707843/1ee0d7fa-0414-11e7-8d06-d4600c7674ad.png)

**Comment by manuszep** [comment]
Duplicate of #36
