### ISSUE TITLE
chevauchement (probable)

### ISSUE THREAD

**Issue by Pinkilla** [manuszep/SEL-Website#41]
lorsqu'il y a plus d'offres, tu numérotes les pages. je pense que je ne peux pas passer à la page suivante. 

![illustration d'un chevauchement](https://cloud.githubusercontent.com/assets/467552/23723281/d59cc9ca-0448-11e7-8467-e777c31ca433.png)

**Comment by manuszep** [comment]
Je n'arrive pas à le reproduire. Il faudra que tu me montre ça sur ta machine.
