### ISSUE TITLE
Ajouter un lien pour avoir la liste complète des échanges (coco)

### ISSUE THREAD

**Issue by manuszep** [manuszep/SEL-Website#55]

**Comment by BernyCawette** [comment]
aaah ça ça va être pratique et intéressant notamment pour la rédaction des articles et des Flash-Infos et newslettres

**Comment by BernyCawette** [comment]
important de pouvoir voir échanges entre qui ? Date et motif ....de préf dans l'ordre antichronologique ( du plus récent au plus vieux  
de plus pour moi les échanges ne devraient pas apparaître sur la page principale du site mais juste chez les personnes concernées par l'échange ( et les Cocos )
